if(OPENSIM_BUILD_INDIVIDUAL_APPS)
    add_executable(analyze analyze.cpp)
    target_link_libraries(analyze PUBLIC osimTools)
    set_target_properties(analyze PROPERTIES FOLDER "Applications")
    install(TARGETS analyze DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()

if(BUILD_TESTING)
    add_subdirectory(test)
endif()
